version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install flake8 coverage coveralls

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . env/bin/activate
            python setup.py test
            flake8 TorchCRF/*.py --show-source --tee --output-file=flake8.txt
            coverage run --source="TorchCRF/" setup.py test
            coverage report
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports
